version: 2

jobs:
  build:
    working_directory: ~/rsf-auth

    docker:
      - image: node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - rsf-auth-{{ .Branch }}-{{ checksum "package.json" }}
            - rsf-auth-{{ .Branch }}
            - rsf-auth-master-{{ checksum "package.json" }}
            - rsf-auth-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Install global dependencies
          command: yarn global add coveralls greenkeeper-lockfile

      - run:
          name: Update lockfile
          command: greenkeeper-lockfile-update

      - run:
          name: Run tests
          command: yarn test:coverage

      - run:
          name: Upload lockfile
          command: greenkeeper-lockfile-upload

      - run:
          name: Send coverage to coveralls.io
          command: |
            if [ -z "$CIRCLE_PR_REPONAME" ];
            then
              cat coverage/lcov.info | coveralls;
            fi

      - save_cache:
          key: rsf-auth-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.config/yarn
            - ~/.yarn
            - ~/rsf-auth/node_modules
